dist: bionic

language: python

arch:
    - amd64
    - arm64

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - sudo apt update
    - sudo apt install flake8 make
    - pip3 install pyyaml autopep8

script:
    - make test
