dist: bionic

language: python

arch:
    - amd64
    - arm64

python:
    - "3.6"
    - "3.7"
    - "3.8"

addons:
    apt:
        update: true
        packages:
            - flake8
            - make

install:
    - pip3 install pyyaml autopep8

script:
    - make test
