dist: bionic

language: python

python:
    - "3.6"
    - "3.7"

install:
    - sudo apt update
    - pip3 install black
    - pip3 install pyyaml

script:
    - python3 -m unittest
    - black --diff --check .
