dist: bionic

language: python

python:
    - "3.6"
    - "3.7"

install:
    - sudo apt update
    - sudo apt install flake8 autopep8
    - pip3 install pyyaml

script:
    - python3 -m unittest
    - flake8
    - autopep8 -r --aggressive --diff --exit-code .
