[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ops"
author = "Gustavo Niemeyer"
author-email = "gustavo.niemeyer@canonical.com"
home-page = "https://github.com/canonical/operator"

