name: Charmcraft Pack Test

on: [push, pull_request, workflow_call]

jobs:
  charmcraft-pack:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Checkout test charm repository
      uses: actions/checkout@v2
      with:
        repository: jnsgruk/hello-kubecon

    - name: Update 'ops' dependency in test charm to latest
      run: |
        # We need to reference the PR branch's repo and commit (not the GITHUB_SHA
        # temporary merge commit), because charmcraft pack does a git checkout which
        # can't see the temporary merge commit.
        sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
        echo -e "\ngit+${{ github.event.pull_request.head.repo.clone_url }}@${{ github.event.pull_request.head.sha }}#egg=ops" >> requirements.txt
        cat requirements.txt

    - name: Install charmcraft
      run: |
          sudo snap refresh lxd --channel=latest
          sudo adduser "$USER" lxd
          sudo lxd init --auto
          sudo snap install charmcraft --classic

    - name: Pack the charm
      run: |
          sudo -g lxd charmcraft pack --verbose
