name: Data Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  db-charm-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/postgresql-operator
            commit: a0c3d8036ec68eca8573fd5b8dee549d3503e42a  # rev464 rev463 2024-08-23T12:27:19Z
          - charm-repo: canonical/postgresql-k8s-operator
            commit: 387a4eca4e6edb32159f69bd32233926826a6b42  # 2024-08-23T12:22:25Z
          - charm-repo: canonical/mysql-operator
            commit: 30505488c189f686d12e514c050f99cc4e0c91ab  # rev275 rev274 2024-08-20T14:48:44Z
          - charm-repo: canonical/mysql-k8s-operator
            commit: a301a4a79febd3f5130598c4a74288a9fc5f8bb1  # 2024-08-22T08:21:59Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Checkout the operator repository
        uses: actions/checkout@v4
        with:
          path: myops

      - name: Install patch dependencies
        run: pip install poetry~=1.6

      - name: Update 'ops' dependency in test charm to latest
        run: |
          if [ -e "requirements.txt" ]; then
            sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
            echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
          else
            sed -i -e "s/^ops[ ><=].*/ops = {path = \"myops\"}/" pyproject.toml
            poetry lock --no-update
          fi

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit
