name: Data Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  db-charm-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/postgresql-operator
            commit: 283463b6df9fd6c81c3221668cbcd4de9927a58d  # rev503 rev502 2024-10-22T11:52:52Z
          - charm-repo: canonical/postgresql-k8s-operator
            commit: fb0276647d1409c67e12459f8b64acca881d0b4a  # 2024-10-24T11:26:42Z
          - charm-repo: canonical/mysql-operator
            commit: 30d63e8d96f8730b5189d95a3f4c0214351801c0  # 2024-10-18T15:50:23Z
          - charm-repo: canonical/mysql-k8s-operator
            commit: b9da8fccd108780bdb551b6dbcac7017f7908990  # 2024-10-18T15:49:54Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Checkout the operator repository
        uses: actions/checkout@v4
        with:
          path: myops

      - name: Install patch dependencies
        run: pip install poetry~=1.6

      - name: Update 'ops' dependency in test charm to latest
        run: |
          if [ -e "requirements.txt" ]; then
            sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
            echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
          else
            sed -i -e "s/^ops[ ><=].*/ops = {path = \"myops\"}/" pyproject.toml
            poetry lock --no-update
          fi

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit
