name: Data Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  db-charm-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/postgresql-operator
            commit: 391935bba89928c6ad3630c72b26232d23570e67  # 2025-01-19T23:39:29Z
          - charm-repo: canonical/postgresql-k8s-operator
            commit: 816d98736b4043182fe323406ab87a80c55bb7f2  # 2025-01-19T23:08:05Z
          - charm-repo: canonical/mysql-operator
            commit: a2ef44b7072013f325163795c486b691a99f6d12  # rev333 rev332 2025-01-17T10:34:37Z
          - charm-repo: canonical/mysql-k8s-operator
            commit: 20c0c0913edc97c7f6748edfc0e8211932422c55  # rev215 rev214 2025-01-17T10:34:55Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Checkout the operator repository
        uses: actions/checkout@v4
        with:
          path: myops

      - name: Install patch dependencies
        run: pip install poetry~=1.6

      - name: Update 'ops' dependency in test charm to latest
        run: |
          if [ -e "requirements.txt" ]; then
            sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
            echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
          else
            sed -i -e "s/^ops[ ><=].*/ops = {path = \"myops\"}/" pyproject.toml
            poetry lock --no-update
          fi

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit
