name: Observability Charm Tests

on: [push, pull_request, workflow_call]

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            commit: 81612b18bf4e9cee072387e75ebd34dff3c189ce  # rev119 2024-06-02T12:08:25Z
          - charm-repo: canonical/prometheus-k8s-operator
            commit: 41b10003b2e7aba34e26fa387af4297d97ecb535  # rev189 2024-05-21T21:25:20Z
          - charm-repo: canonical/grafana-k8s-operator
            commit: fd6a7da88fa044709be69a4c733d879eb7175b54  # rev114 2024-05-29T09:55:04Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        run: tox -vve static-charm
