name: Observability Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            commit: 5ca6dbbbd42db2d6c5ce58575759fd8cfc27d4ca  # rev147 2025-01-16T13:58:33Z
          - charm-repo: canonical/prometheus-k8s-operator
            commit: 55b9696619aceb5cdbccea522cf35cebe0420244 # 2025-01-16T16:01:17Z
            disabled: true # Waiting for an upstream PR: https://github.com/canonical/prometheus-k8s-operator/pull/639
          - charm-repo: canonical/grafana-k8s-operator
            commit: 00a30fc07f1dff37f3167a14c037f70a13fdfa39  # rev133 2025-01-16T14:15:32Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        if: ${{ !(matrix.disabled) }}
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        if: ${{ !(matrix.disabled) }}
        run: tox -vve static-charm
