name: Observability Charm Tests

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_call:

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            commit: 537183470450e231db1568c1462445ef2ef4a02a  # rev120 2024-06-07T12:11:09Z
          - charm-repo: canonical/prometheus-k8s-operator
            commit: 051a3a750e057bf97ba44335b3a66261dd3e78a6  # rev196 2024-06-07T16:01:22Z
          - charm-repo: canonical/grafana-k8s-operator
            commit: c9eca75596bee7b5e5bf977bf0f6b8b4c3116e5e  # 2024-06-03T20:26:50Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        run: tox -vve static-charm
