name: Publish
on:
  release:
    types:
      - published

jobs:
  framework-tests:
    uses: ./.github/workflows/framework-tests.yaml
  observability-charm-tests:
    uses: ./.github/workflows/observability-charm-tests.yaml
  hello-charm-tests:
    uses: ./.github/workflows/hello-charm-tests.yaml
  build-n-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: [framework-tests, observability-charm-tests, hello-charm-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install build dependencies
        run: pip install wheel build
      - name: Build
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
