name: Publish
on:
  release:
    types:
      - published

jobs:
  build-n-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build
        run: python setup.py bdist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@main
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
