name: ops Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 25 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # pylibjuju does not currently support Juju 4.x
        # The smoke tests do not yet work on Juju 2.9.
        juju-channel: ['3/stable']
        charmcraft-channel: ['2.x/stable', '3.x/stable']
        preset: ['machine', 'microk8s']

    env:
      CONCIERGE_JUJU_CHANNEL: "${{ matrix.juju-channel }}"
      CONCIERGE_CHARMCRAFT_CHANNEL: "${{ matrix.charmcraft-channel }}"

    steps:
      - name: Install concierge
        run: sudo snap install --classic concierge

      - name: Install Juju and tools
        run: sudo concierge prepare -p "${{ matrix.preset }}"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5

      - name: Install tox
        run: pip install tox~=4.2

      - name: Run smoke tests
        run: tox -e smoke
